#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18052
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("myOxyPlot.Resource", IsApplication=true)]

namespace myOxyPlot
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int goldronze = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Welcom = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int ConfirmButton = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int LinearLayout01 = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout02 = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int LinearLayout03 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int TextView01 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int TextView02 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int TextView03 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int TextView04 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int TextView05 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int dialog = 2131165185;
			
			// aapt resource value: 0x7f07000d
			public const int plotview = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int xAxisCheckBox = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int yAxisCheckBox = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int zAxisCheckBox = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AxisChoice = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SensorUnavailable = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Wykres = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AxesToPlot = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int ConfirmButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int xAxis = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int yAxis = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int zAxis = 2131034116;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int Theme_AxesChoice = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int Theme_NotSupported = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Theme_Plot = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
